paths: 
  /api/products/:
    get:
      summary: Get products.
      tags: 
        - Products
      responses: 
        "200":
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: An error occurred processing the request
    post:
      summary: Create a new product
      tags:
        - Products
      requestBody:
        required: true
        description: Create a new product
        $ref: "#components/requestBodies/createProduct"
      responses: 
        "200":
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "400" : 
          description: Error to create product          
        "500":
          description: An error occurred processing the request
  /api/products/{pid}:
    get:
      summary: Gets a single product from its id
      tags: 
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID of the product you wish to request
        schema:
          $type: String
      responses:
        "200":
          description: The requested product 
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "404" : Id not found
    put:
      summary: Update product by id
      tags: 
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: product id to update
        schema:
          $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
            responses:
        "200":
          description: The requested product was updated
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "404" : Id not found
    delete:
      summary: Delete product by id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: id to delete a product
          schema:
            $type: String
      responses:
        '200':
          description: the requested product has been deleted
        '404':
          description: Id not found
components:
  schemas:
    Product:
      type: object
      properties:
        _id : 
          type: ObjectId
          description: Mongo autogenerated Id
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Description of product
        price:
          type: number
          description: price of the product
        thumbnail:
          type: array
          description: array of product images
        code:
          type: string
          description: unique code of product
        stock:
          type: number
          description: stock of the product
        status: 
          type: boolean
          description: product status
        category:
          type: string
          description: category of the product
        owner:
          type: string
          description: user that owns this product
      example:
        _id: ObjectId("65a1ab4be75e71bdfd8b1f51")
        title: "Mushroom - Shitake, Fresh"
        description: "Mushroom - Shitake, Fresh"
        price: 726.7
        thumbnail: []
        stock: 37
        code: "GB68 TFUI 0812 9911 7310 12"
        status: true
        category: "Computers"
        owner: "prueba@prueba.com"
  requestBodies:
    createProduct:
      type: object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/createProduct"
            properties:
              title:
                type: string
                description: Title of new product
              description:
                type: string
                description: Description of new product
              price:
                type: number
                description: Price of new product
              code:
                type: string
                description: Unique code of new product
              stock:
                type: number
                description: Stock of new product
              status:
                type: boolean
                description: Status of new product
              category:
                type: string
                description: Category of new product
              owner:
                type: string
                description: email who owns the product
            example:
              title: "Notebook"
              description: "Notebook I9 8GB RAM"
              price: 1200.9
              thumbnail: []
              stock: 3
              code: "AA68 99UI TT12 9911 7310 12"
              status: true
              category: "Computers"
              owner: "prueba@prueba.com"
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Title of new product
        description:
          type: string
          description: Description of new product
        price:
          type: number
          description: Price of new product
        code:
          type: string
          description: Unique code of new product
        stock:
          type: number
          description: Stock of new product
        status:
          type: boolean
          description: Status of new product
        category:
          type: string
          description: Category of new product
        owner:
          type: string
          description: email who owns the product
      example:
        title: "Notebook"
        description: "Notebook I9 8GB RAM"
        price: 1200.9
        thumbnail: []
        stock: 3
        code: "AA68 99UI TT12 9911 7310 12"
        status: true
        category: "Computers"
        owner: "prueba@prueba.com"