const ErrorEnum = {
    ROUTING_ERROR: 1,
    INVALID_TYPE_ERROR: 2,
    DATABASE_ERROR: 3,
    USER_NOT_FOUND: 4,
    ID_NOT_FOUND: 5,
    EXCEEDS_STOCK: 6,
    INVALID_PARAM: 7,
    PREMIUM_ERROR_ADD_PRODUCT: 8
}

export default ErrorEnum;